version: '3'

services:
  app:
    container_name: weather-status-app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: wsa-mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: weather_status_app
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'